In [2]:
import pandas as pd

# Load the dataset
df_BO = pd.read_csv('prediction_statistic.csv')
df_Cma = pd.read_csv('predictions_CmaEs.csv')
df_GA2 = pd.read_csv('predictions_NSGAII.csv')
df_GA3 = pd.read_csv('predictions_NSGAIII.csv')
df_QMC = pd.read_csv('predictions_QMC.csv')
df_TPE = pd.read_csv('predictions_TPESampler.csv')
df_Random = pd.read_csv('predictions_RandomSampler.csv')

df = pd.concat([df_BO, df_Cma, df_GA2, df_GA3, df_QMC, df_TPE, df_Random], axis=1, ignore_index=True)
df

,0,1,2,3,4,5,6,7,8,9,...,61,62,63,64,65,66,67,68,69,70
0,15.342130,15.204589,2.272135e-01,15.154456,15.097291,14.465214,15.140710,14.157033,14.474430,8.974268,...,15.342130,13.333864,2.272060e-01,15.154456,15.138342,14.207445,14.908165,12.489426,15.316147,11.728402
1,13.411457,10.611166,1.250000e-26,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.230490,...,13.411457,8.044213,1.247845e-26,15.154456,15.138342,12.886855,14.908165,12.671637,15.520970,12.457241
2,13.411457,6.348708,0.000000e+00,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.764193,...,13.411457,5.867585,0.000000e+00,15.154456,15.138342,12.886855,14.908165,12.671637,15.520970,13.808187
3,13.411457,10.783257,9.820000e-22,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.046995,...,13.411457,8.353090,9.817656e-22,15.154456,15.138342,12.886855,14.908165,12.671637,15.520970,12.169364
4,13.411457,7.021644,1.399995e-313,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.301709,...,13.411457,5.871094,1.399961e-313,15.154456,15.138342,12.886855,14.908165,12.671637,15.520970,12.853203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8911,13.020945,6.321873,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.200484,...,13.020945,5.867585,0.000000e+00,13.831947,13.676040,11.977497,13.275103,12.685903,13.740953,11.872126
8912,13.020945,6.321872,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.180530,...,13.020945,5.867585,0.000000e+00,13.831947,13.676040,11.977497,13.275103,12.685903,13.740953,11.863396
8913,13.020945,6.321871,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.160577,...,13.020945,5.867585,0.000000e+00,13.831947,13.676040,11.977497,13.275103,12.685903,13.740953,11.854666
8914,13.020945,6.321870,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.140624,...,13.020945,5.867585,0.000000e+00,13.831947,13.676040,11.977497,13.275103,12.685903,13.740953,11.845935
8915,13.020945,6.321869,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.120670,...,13.020945,5.867585,0.000000e+00,13.831947,13.676040,11.977497,13.275103,12.685903,13.740953,11.837205

In [3]:
df[df < 0] = 0

In [4]:
df['mean'] = df.mean(axis=1)
df['std'] = df.std(axis=1)
df

,0,1,2,3,4,5,6,7,8,9,...,63,64,65,66,67,68,69,70,mean,std
0,15.342130,15.204589,2.272135e-01,15.154456,15.097291,14.465214,15.140710,14.157033,14.474430,8.974268,...,2.272060e-01,15.154456,15.138342,14.207445,14.908165,12.489426,15.316147,11.728402,12.633083,4.745519
1,13.411457,10.611166,1.250000e-26,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.230490,...,1.247845e-26,15.154456,15.138342,12.886855,14.908165,12.671637,15.520970,12.457241,11.982006,4.720522
2,13.411457,6.348708,0.000000e+00,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.764193,...,0.000000e+00,15.154456,15.138342,12.886855,14.908165,12.671637,15.520970,13.808187,11.749051,4.982300
3,13.411457,10.783257,9.820000e-22,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.046995,...,9.817656e-22,15.154456,15.138342,12.886855,14.908165,12.671637,15.520970,12.169364,12.014190,4.643342
4,13.411457,7.021644,1.399995e-313,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.301709,...,1.399961e-313,15.154456,15.138342,12.886855,14.908165,12.671637,15.520970,12.853203,11.737306,4.883244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8911,13.020945,6.321873,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.200484,...,0.000000e+00,13.831947,13.676040,11.977497,13.275103,12.685903,13.740953,11.872126,136.379870,1048.776972
8912,13.020945,6.321872,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.180530,...,0.000000e+00,13.831947,13.676040,11.977497,13.275103,12.685903,13.740953,11.863396,136.391817,1048.895066
8913,13.020945,6.321871,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.160577,...,0.000000e+00,13.831947,13.676040,11.977497,13.275103,12.685903,13.740953,11.854666,136.403764,1049.013160
8914,13.020945,6.321870,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.140624,...,0.000000e+00,13.831947,13.676040,11.977497,13.275103,12.685903,13.740953,11.845935,136.415712,1049.131255
8915,13.020945,6.321869,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.120670,...,0.000000e+00,13.831947,13.676040,11.977497,13.275103,12.685903,13.740953,11.837205,136.427659,1049.249349

In [5]:
from scipy.stats import norm
z_40 = norm.ppf(0.7)
z_80 = norm.ppf(0.9)
z_95 = norm.ppf(0.975)

df['lower_bound_40'] = df['mean'] - z_40 * df['std']
df['upper_bound_40'] = df['mean'] + z_40 * df['std']

df['lower_bound_80'] = df['mean'] - z_80 * df['std']
df['upper_bound_80'] = df['mean'] + z_80 * df['std']

df['lower_bound_95'] = df['mean'] - z_95 * df['std']
df['upper_bound_95'] = df['mean'] + z_95 * df['std']

df

,0,1,2,3,4,5,6,7,8,9,...,69,70,mean,std,lower_bound_40,upper_bound_40,lower_bound_80,upper_bound_80,lower_bound_95,upper_bound_95
0,15.342130,15.204589,2.272135e-01,15.154456,15.097291,14.465214,15.140710,14.157033,14.474430,8.974268,...,15.316147,11.728402,12.633083,4.745519,10.144530,15.121636,6.551455,18.714710,3.332036,21.934130
1,13.411457,10.611166,1.250000e-26,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.230490,...,15.520970,12.457241,11.982006,4.720522,9.506562,14.457451,5.932414,18.031599,2.729953,21.234060
2,13.411457,6.348708,0.000000e+00,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.764193,...,15.520970,13.808187,11.749051,4.982300,9.136331,14.361772,5.363977,18.134125,1.983924,21.514179
3,13.411457,10.783257,9.820000e-22,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.046995,...,15.520970,12.169364,12.014190,4.643342,9.579219,14.449162,6.063507,17.964873,2.913406,21.114974
4,13.411457,7.021644,1.399995e-313,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.301709,...,15.520970,12.853203,11.737306,4.883244,9.176530,14.298082,5.479176,17.995435,2.166323,21.308289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8911,13.020945,6.321873,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.200484,...,13.740953,11.872126,136.379870,1048.776972,-413.599312,686.359052,-1207.681900,1480.441640,-1919.185223,2191.944963
8912,13.020945,6.321872,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.180530,...,13.740953,11.863396,136.391817,1048.895066,-413.649293,686.432928,-1207.821297,1480.604931,-1919.404736,2192.188371
8913,13.020945,6.321871,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.160577,...,13.740953,11.854666,136.403764,1049.013160,-413.699275,686.506804,-1207.960694,1480.768222,-1919.624249,2192.431778
8914,13.020945,6.321870,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.140624,...,13.740953,11.845935,136.415712,1049.131255,-413.749256,686.580679,-1208.100090,1480.931514,-1919.843763,2192.675186
8915,13.020945,6.321869,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.120670,...,13.740953,11.837205,136.427659,1049.249349,-413.799238,686.654555,-1208.239487,1481.094805,-1920.063276,2192.918594

In [6]:
models = 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69
df['probability_40'] = df.apply(lambda row: sum([1 for model in models if row[model] >= row['lower_bound_40'] and row[model] <= row['upper_bound_40']]) / len(models), axis=1)
df['probability_80'] = df.apply(lambda row: sum([1 for model in models if row[model] >= row['lower_bound_80'] and row[model] <= row['upper_bound_80']]) / len(models), axis=1)
df['probability_95'] = df.apply(lambda row: sum([1 for model in models if row[model] >= row['lower_bound_95'] and row[model] <= row['upper_bound_95']]) / len(models), axis=1)
df

,0,1,2,3,4,5,6,7,8,9,...,std,lower_bound_40,upper_bound_40,lower_bound_80,upper_bound_80,lower_bound_95,upper_bound_95,probability_40,probability_80,probability_95
0,15.342130,15.204589,2.272135e-01,15.154456,15.097291,14.465214,15.140710,14.157033,14.474430,8.974268,...,4.745519,10.144530,15.121636,6.551455,18.714710,3.332036,21.934130,0.385714,0.885714,0.885714
1,13.411457,10.611166,1.250000e-26,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.230490,...,4.720522,9.506562,14.457451,5.932414,18.031599,2.729953,21.234060,0.357143,0.885714,0.885714
2,13.411457,6.348708,0.000000e+00,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.764193,...,4.982300,9.136331,14.361772,5.363977,18.134125,1.983924,21.514179,0.285714,0.885714,0.900000
3,13.411457,10.783257,9.820000e-22,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.046995,...,4.643342,9.579219,14.449162,6.063507,17.964873,2.913406,21.114974,0.357143,0.885714,0.900000
4,13.411457,7.021644,1.399995e-313,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.301709,...,4.883244,9.176530,14.298082,5.479176,17.995435,2.166323,21.308289,0.300000,0.885714,0.900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8911,13.020945,6.321873,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.200484,...,1048.776972,-413.599312,686.359052,-1207.681900,1480.441640,-1919.185223,2191.944963,0.985714,0.985714,0.985714
8912,13.020945,6.321872,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.180530,...,1048.895066,-413.649293,686.432928,-1207.821297,1480.604931,-1919.404736,2192.188371,0.985714,0.985714,0.985714
8913,13.020945,6.321871,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.160577,...,1049.013160,-413.699275,686.506804,-1207.960694,1480.768222,-1919.624249,2192.431778,0.985714,0.985714,0.985714
8914,13.020945,6.321870,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.140624,...,1049.131255,-413.749256,686.580679,-1208.100090,1480.931514,-1919.843763,2192.675186,0.985714,0.985714,0.985714
8915,13.020945,6.321869,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.120670,...,1049.249349,-413.799238,686.654555,-1208.239487,1481.094805,-1920.063276,2192.918594,0.985714,0.985714,0.985714

In [7]:
df.drop(['std', 'lower_bound_40', 'upper_bound_40', 'lower_bound_80', 'upper_bound_80', 'lower_bound_95', 'upper_bound_95'], axis=1, inplace=True)
df

,0,1,2,3,4,5,6,7,8,9,...,65,66,67,68,69,70,mean,probability_40,probability_80,probability_95
0,15.342130,15.204589,2.272135e-01,15.154456,15.097291,14.465214,15.140710,14.157033,14.474430,8.974268,...,15.138342,14.207445,14.908165,12.489426,15.316147,11.728402,12.633083,0.385714,0.885714,0.885714
1,13.411457,10.611166,1.250000e-26,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.230490,...,15.138342,12.886855,14.908165,12.671637,15.520970,12.457241,11.982006,0.357143,0.885714,0.885714
2,13.411457,6.348708,0.000000e+00,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.764193,...,15.138342,12.886855,14.908165,12.671637,15.520970,13.808187,11.749051,0.285714,0.885714,0.900000
3,13.411457,10.783257,9.820000e-22,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.046995,...,15.138342,12.886855,14.908165,12.671637,15.520970,12.169364,12.014190,0.357143,0.885714,0.900000
4,13.411457,7.021644,1.399995e-313,15.154456,15.086314,15.055318,15.140710,14.197360,13.928133,9.301709,...,15.138342,12.886855,14.908165,12.671637,15.520970,12.853203,11.737306,0.300000,0.885714,0.900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8911,13.020945,6.321873,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.200484,...,13.676040,11.977497,13.275103,12.685903,13.740953,11.872126,136.379870,0.985714,0.985714,0.985714
8912,13.020945,6.321872,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.180530,...,13.676040,11.977497,13.275103,12.685903,13.740953,11.863396,136.391817,0.985714,0.985714,0.985714
8913,13.020945,6.321871,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.160577,...,13.676040,11.977497,13.275103,12.685903,13.740953,11.854666,136.403764,0.985714,0.985714,0.985714
8914,13.020945,6.321870,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.140624,...,13.676040,11.977497,13.275103,12.685903,13.740953,11.845935,136.415712,0.985714,0.985714,0.985714
8915,13.020945,6.321869,0.000000e+00,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.120670,...,13.676040,11.977497,13.275103,12.685903,13.740953,11.837205,136.427659,0.985714,0.985714,0.985714

In [8]:
import numpy as np
df['entropy'] = -df['probability_40']*np.log2(df['probability_40']) - df['probability_80']*np.log2(df['probability_80']) - df['probability_95']*np.log2(df['probability_95'])
df[df['entropy']==df['entropy'].max()]

,0,1,2,3,4,5,6,7,8,9,...,66,67,68,69,70,mean,probability_40,probability_80,probability_95,entropy
18,14.28016,10.5678,3.808426,13.085841,13.415496,16.916374,16.723075,11.952234,14.947906,8.68962,...,14.440007,15.143646,11.206605,17.660671,11.06573,12.486946,0.457143,0.828571,0.9,0.87784
19,14.28016,10.5678,3.808426,13.085841,13.415496,16.916374,16.723075,11.952234,14.947906,8.68962,...,14.440007,15.143646,11.206605,17.660671,11.06573,12.501030,0.457143,0.828571,0.9,0.87784

In [9]:
df['max_prob'] = df[['probability_40', 'probability_80', 'probability_95']].max(axis=1)
df[df['max_prob']==df['max_prob'].min()]

,0,1,2,3,4,5,6,7,8,9,...,67,68,69,70,mean,probability_40,probability_80,probability_95,entropy,max_prob
12,8.496486,8.335643,8.790000e-15,7.424316,8.335449,7.680407,7.759821,9.764978,8.704210,8.781901,...,9.148456,9.694060,7.491001,11.020591,7.554109,0.628571,0.842857,0.871429,0.801950,0.871429
22,8.696166,10.326495,3.620000e-16,8.172253,8.108602,8.365530,8.171143,8.564230,9.519327,8.361576,...,8.395565,8.236030,8.229893,10.291644,7.924486,0.771429,0.871429,0.871429,0.634856,0.871429
23,8.496486,8.501955,3.430000e-06,8.367191,8.367056,9.319403,8.429168,9.051360,9.583974,8.543514,...,7.896198,9.749748,8.260859,10.780101,8.066296,0.828571,0.871429,0.871429,0.570830,0.871429

In [10]:
df['margin'] = df[['probability_40', 'probability_80', 'probability_95']].apply(lambda x: sorted(x)[-1] - sorted(x)[-2] if sorted(x)[-1] != sorted(x)[-2] else sorted(x)[-1] - sorted(x)[-3], axis=1)
df[df['margin']==df['margin'].min()]

,0,1,2,3,4,5,6,7,8,9,...,68,69,70,mean,probability_40,probability_80,probability_95,entropy,max_prob,margin
101,1.232275,6.318293,0.0,4.380139,4.373201,4.114161,4.339345,1.564696,4.530481,5.942977,...,2.218356,4.122794,3.270517,4.985429,0.985714,0.985714,0.985714,0.061386,0.985714,0.0
110,1.326992,6.318293,0.0,0.378866,0.387538,0.431622,0.393309,1.194003,1.987930,5.763396,...,1.676561,0.169777,3.191944,3.186739,0.985714,0.985714,0.985714,0.061386,0.985714,0.0
111,1.326992,6.318293,0.0,0.378866,0.387538,0.431622,0.393309,1.194003,1.987930,5.743443,...,1.676561,0.169777,3.183214,3.198858,0.985714,0.985714,0.985714,0.061386,0.985714,0.0
112,1.326992,6.318293,0.0,0.378866,0.387538,0.431622,0.393309,1.194003,1.987930,5.723489,...,1.676561,0.169777,3.174483,3.210976,0.985714,0.985714,0.985714,0.061386,0.985714,0.0
113,1.326992,6.318293,0.0,0.378866,0.387538,0.431622,0.393309,1.194003,1.987930,5.703536,...,1.676561,0.169777,3.165753,3.223095,0.985714,0.985714,0.985714,0.061386,0.985714,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8911,13.020945,6.321873,0.0,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.200484,...,12.685903,13.740953,11.872126,136.379870,0.985714,0.985714,0.985714,0.061386,0.985714,0.0
8912,13.020945,6.321872,0.0,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.180530,...,12.685903,13.740953,11.863396,136.391817,0.985714,0.985714,0.985714,0.061386,0.985714,0.0
8913,13.020945,6.321871,0.0,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.160577,...,12.685903,13.740953,11.854666,136.403764,0.985714,0.985714,0.985714,0.061386,0.985714,0.0
8914,13.020945,6.321870,0.0,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.140624,...,12.685903,13.740953,11.845935,136.415712,0.985714,0.985714,0.985714,0.061386,0.985714,0.0
8915,13.020945,6.321869,0.0,13.831947,13.599419,13.628506,13.599381,14.055867,14.818588,8.120670,...,12.685903,13.740953,11.837205,136.427659,0.985714,0.985714,0.985714,0.061386,0.985714,0.0

In [11]:
entropy_max = df[df['entropy']==df['entropy'].max()]
max_prob_min = df[df['max_prob']==df['max_prob'].min()]
margin_max = df[df['margin']==df['margin'].max()]

common_indices = set(entropy_max.index) & set(max_prob_min.index) & set(margin_max.index)

# Extracting the common rows based on the indices
common_rows = df[df['max_prob']==df['max_prob'].min()]

common_rows

,0,1,2,3,4,5,6,7,8,9,...,68,69,70,mean,probability_40,probability_80,probability_95,entropy,max_prob,margin
12,8.496486,8.335643,8.790000e-15,7.424316,8.335449,7.680407,7.759821,9.764978,8.704210,8.781901,...,9.694060,7.491001,11.020591,7.554109,0.628571,0.842857,0.871429,0.801950,0.871429,0.028571
22,8.696166,10.326495,3.620000e-16,8.172253,8.108602,8.365530,8.171143,8.564230,9.519327,8.361576,...,8.236030,8.229893,10.291644,7.924486,0.771429,0.871429,0.871429,0.634856,0.871429,0.100000
23,8.496486,8.501955,3.430000e-06,8.367191,8.367056,9.319403,8.429168,9.051360,9.583974,8.543514,...,9.749748,8.260859,10.780101,8.066296,0.828571,0.871429,0.871429,0.570830,0.871429,0.042857

In [12]:
common_rows.index

Index([12, 22, 23], dtype='int64')

In [13]:
train_df = pd.read_csv(r'C:\Users\OJH\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Database\Na_W_Mn_Cat_train_rev.csv')
test_df = pd.read_csv(r'C:\Users\OJH\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Database\Na_W_Mn_Cat_test_rev.csv')

# Extracting the independent variables (X) and the dependent variable (y)
X_train = train_df[['Temperature', 'pCH4_per_pO2', 'Contact time']]
y_train = train_df['Y(C2)_predicted']
X_test = test_df[['Temperature', 'pCH4_per_pO2', 'Contact time']]
y_test = test_df['Y(C2)_predicted']

# Determining the range of each variable in the training data
train_range = {
    'Temperature': (X_train['Temperature'].min(), X_train['Temperature'].max()),
    'pCH4_per_pO2': (X_train['pCH4_per_pO2'].min(), X_train['pCH4_per_pO2'].max()),
    'Contact time': (X_train['Contact time'].min(), X_train['Contact time'].max())
}
# Function to determine the extrapolation strength for a given observation
def determine_extrapolation_strength(row, train_range):
    strength = 0
    for col in train_range:
        if row[col] < train_range[col][0] or row[col] > train_range[col][1]:
            strength += 1
    return strength

# Applying the function to the test data
test_df['Extrapolation Strength'] = test_df.apply(lambda row: determine_extrapolation_strength(row, train_range), axis=1)

def identify_extrapolating_variables(row, train_range):
    extrapolating_vars = []
    for col in train_range:
        if row[col] < train_range[col][0] or row[col] > train_range[col][1]:
            extrapolating_vars.append(col)
    return extrapolating_vars

# Applying the function to the test data
test_df['Extrapolating Variables'] = test_df.apply(lambda row: identify_extrapolating_variables(row, train_range), axis=1)

# Filtering the test data for extrapolation strengths 1 and 2
extrapolation_1_df = test_df[test_df['Extrapolation Strength'] == 1]
extrapolation_2_df = test_df[test_df['Extrapolation Strength'] == 2]

# Identifying the unique combinations of extrapolating variables for extrapolation strengths 1 and 2
unique_extrapolating_vars_1 = extrapolation_1_df['Extrapolating Variables'].value_counts()
unique_extrapolating_vars_2 = extrapolation_2_df['Extrapolating Variables'].value_counts()

total_common_rows = test_df.merge(common_rows, left_index=True, right_index=True)

In [14]:
total_common_rows

,Temperature,pCH4_per_pO2,Contact time,Y(C2)_predicted,Extrapolation Strength,Extrapolating Variables,0,1,2,3,...,68,69,70,mean,probability_40,probability_80,probability_95,entropy,max_prob,margin
12,1056.0,1.8,0.04,8.897596,1,[pCH4_per_pO2],8.496486,8.335643,8.790000e-15,7.424316,...,9.694060,7.491001,11.020591,7.554109,0.628571,0.842857,0.871429,0.801950,0.871429,0.028571
22,1033.0,2.0,0.55,17.949246,1,[pCH4_per_pO2],8.696166,10.326495,3.620000e-16,8.172253,...,8.236030,8.229893,10.291644,7.924486,0.771429,0.871429,0.871429,0.634856,0.871429,0.100000
23,1053.0,2.0,0.55,17.549025,1,[pCH4_per_pO2],8.496486,8.501955,3.430000e-06,8.367191,...,9.749748,8.260859,10.780101,8.066296,0.828571,0.871429,0.871429,0.570830,0.871429,0.042857

In [15]:
total_common_rows.to_csv('active_learning_candidates_original.csv')